import type { Insumo } from "@/lib/repositories/insumos";
import type { Produto } from "@/lib/repositories/produtos";
import type { Encomenda } from "@/lib/repositories/encomendas";
import type { Pagamento } from "@/lib/repositories/pagamentos";
import type { ProdutoPE } from "@/lib/repositories/pronta-entrega";
import type { CustoIndireto } from "@/lib/repositories/financeiro";
import type { Configuracoes } from "@/lib/repositories/configuracoes";

export const insumosSeed: Insumo[] = [
  {
    id: "ins-1",
    nome: "Papel Color Plus 180g",
    categoria: "visivel",
    unidade: "folha",
    precoAtual: 1.35,
    estoque: 240,
    estoqueMin: 100,
    fornecedor: "Papelaria Central",
    historico: [
      { data: "2026-04-01", preco: 1.2 },
      { data: "2026-06-01", preco: 1.35 },
    ],
  },
  {
    id: "ins-2",
    nome: "Papel Kraft 180g",
    categoria: "visivel",
    unidade: "folha",
    precoAtual: 0.95,
    estoque: 80,
    estoqueMin: 100,
    fornecedor: "Papelaria Central",
    historico: [{ data: "2026-05-10", preco: 0.95 }],
  },
  {
    id: "ins-3",
    nome: "Cola Quente (bastão)",
    categoria: "invisivel",
    unidade: "unidade",
    precoAtual: 0.6,
    estoque: 150,
    estoqueMin: 40,
    fornecedor: "Casa das Colas",
    historico: [
      { data: "2026-03-01", preco: 0.55 },
      { data: "2026-06-01", preco: 0.6 },
    ],
  },
  {
    id: "ins-4",
    nome: "Filamento PLA Branco",
    categoria: "invisivel",
    unidade: "g",
    precoAtual: 0.09,
    estoque: 1200,
    estoqueMin: 500,
    fornecedor: "3D Prime",
    historico: [
      { data: "2026-05-01", preco: 0.08 },
      { data: "2026-06-20", preco: 0.09 },
    ],
  },
  {
    id: "ins-5",
    nome: "Tesoura de precisão",
    categoria: "ferramenta",
    unidade: "unidade",
    precoAtual: 32,
    estoque: null,
    estoqueMin: null,
    historico: [],
  },
  {
    id: "ins-6",
    nome: "Estilete profissional",
    categoria: "ferramenta",
    unidade: "unidade",
    precoAtual: 18,
    estoque: null,
    estoqueMin: null,
    historico: [],
  },
  {
    id: "ins-7",
    nome: "Impressora 3D Bambu Lab A1",
    categoria: "maquinario",
    unidade: "unidade",
    precoAtual: 2899,
    estoque: null,
    estoqueMin: null,
    historico: [],
  },
  {
    id: "ins-8",
    nome: "Plotter de recorte Silhouette",
    categoria: "maquinario",
    unidade: "unidade",
    precoAtual: 1850,
    estoque: null,
    estoqueMin: null,
    historico: [],
  },
];

export const produtosSeed: Produto[] = [
  {
    id: "prod-1",
    nome: "Caderno Artesanal A5",
    categoria: "Planner",
    receita: [
      { insumoId: "ins-1", quantidade: 40 },
      { insumoId: "ins-3", quantidade: 2 },
    ],
    tempoProducao: 50,
    custo: 32,
    precoSugerido: 96,
    margem: 66.7,
    prontoEstoque: 8,
    prontoEstoqueMin: 5,
    historicoLotes: [
      { id: "lote-1", produtoId: "prod-1", quantidade: 10, data: "2026-06-10", observacao: "Lote inicial" },
    ],
  },
  {
    id: "prod-2",
    nome: "Chaveiro 3D Personalizado",
    categoria: "Chaveiro",
    receita: [{ insumoId: "ins-4", quantidade: 15 }],
    tempoProducao: 25,
    custo: 6.5,
    precoSugerido: 22,
    margem: 70.5,
    etapas3D: { impressao: 20, modelagem: 15, acabamento: 5 },
    prontoEstoque: 34,
    prontoEstoqueMin: 20,
    historicoLotes: [
      { id: "lote-2", produtoId: "prod-2", quantidade: 50, data: "2026-06-05" },
      { id: "lote-3", produtoId: "prod-2", quantidade: 30, data: "2026-07-01" },
    ],
  },
  {
    id: "prod-3",
    nome: "Kit Convite de Casamento",
    categoria: "Kit",
    receita: [
      { insumoId: "ins-1", quantidade: 20 },
      { insumoId: "ins-2", quantidade: 10 },
      { insumoId: "ins-3", quantidade: 1 },
    ],
    tempoProducao: 120,
    custo: 85,
    precoSugerido: 255,
    margem: 66.7,
  },
  {
    id: "prod-4",
    nome: "Tag para presente",
    categoria: "Tag",
    receita: [{ insumoId: "ins-2", quantidade: 5 }],
    tempoProducao: 10,
    custo: 3.2,
    precoSugerido: 9.5,
    margem: 66.3,
    prontoEstoque: 15,
    prontoEstoqueMin: 20,
  },
];

export const encomendasSeed: Encomenda[] = [
  {
    id: "enc-1",
    cliente: "Marina Silva",
    canal: "whatsapp",
    status: "aguardando",
    dataPedido: "2026-07-10",
    dataEntrega: "2026-07-20",
    itens: [{ produtoId: "prod-3", quantidade: 1, precoUnitario: 255 }],
    desconto: 0,
    totalCobrado: 255,
    custoProducao: 85,
    margem: 66.7,
    observacoes: "Casamento no dia 25.",
    linksUteis: [],
  },
  {
    id: "enc-2",
    cliente: "João Pedro",
    canal: "presencial",
    status: "em_producao",
    dataPedido: "2026-07-08",
    dataEntrega: "2026-07-18",
    itens: [{ produtoId: "prod-2", quantidade: 5, precoUnitario: 22 }],
    desconto: 5,
    totalCobrado: 105,
    custoProducao: 32.5,
    margem: 69,
    observacoesInternas: "Gravar nomes personalizados antes do acabamento.",
    linksUteis: [{ id: "link-1", label: "Referência Pinterest", url: "https://pinterest.com/exemplo" }],
  },
  {
    id: "enc-3",
    cliente: "Ateliê Flor de Lis",
    canal: "whatsapp",
    status: "pronto",
    dataPedido: "2026-07-01",
    dataEntrega: "2026-07-16",
    itens: [{ produtoId: "prod-1", quantidade: 3, precoUnitario: 96 }],
    desconto: 0,
    totalCobrado: 288,
    custoProducao: 96,
    margem: 66.7,
    linksUteis: [],
  },
  {
    id: "enc-4",
    cliente: "Camila Souza",
    canal: "presencial",
    status: "entregue",
    dataPedido: "2026-06-20",
    dataEntrega: "2026-07-05",
    itens: [{ produtoId: "prod-4", quantidade: 20, precoUnitario: 9.5 }],
    desconto: 0,
    totalCobrado: 190,
    custoProducao: 64,
    margem: 66.3,
    linksUteis: [],
  },
  {
    id: "enc-5",
    cliente: "Rafael Costa",
    canal: "whatsapp",
    status: "entregue",
    dataPedido: "2026-06-15",
    dataEntrega: "2026-06-28",
    itens: [{ produtoId: "prod-2", quantidade: 10, precoUnitario: 22 }],
    desconto: 10,
    totalCobrado: 210,
    custoProducao: 65,
    margem: 69,
    linksUteis: [],
  },
];

export const pagamentosSeed: Pagamento[] = [
  { id: "pag-1", encomendaId: "enc-2", valor: 50, metodo: "pix", data: "2026-07-08", tipo: "recebimento" },
  { id: "pag-2", encomendaId: "enc-3", valor: 288, metodo: "cartao", data: "2026-07-14", tipo: "recebimento" },
  { id: "pag-3", encomendaId: "enc-4", valor: 190, metodo: "dinheiro", data: "2026-07-05", tipo: "recebimento" },
  { id: "pag-4", encomendaId: "enc-5", valor: 210, metodo: "pix", data: "2026-06-28", tipo: "recebimento" },
];

export const produtosPeSeed: ProdutoPE[] = [
  {
    id: "pe-1",
    nome: "Bloco de Notas Adesivo",
    descricao: "Bloco com 50 folhas coloridas",
    precoVenda: 18,
    estoqueAtual: 22,
    estoqueMin: 10,
  },
  {
    id: "pe-2",
    nome: "Marcador de Página 3D",
    descricao: "Design floral em PLA",
    precoVenda: 12,
    estoqueAtual: 5,
    estoqueMin: 10,
  },
  {
    id: "pe-3",
    nome: "Caixa Organizadora Pequena",
    descricao: "Papelão rígido revestido",
    precoVenda: 35,
    estoqueAtual: 14,
    estoqueMin: 5,
  },
];

export const custosIndiretosSeed: CustoIndireto[] = [
  { id: "custo-1", nome: "Aluguel do ateliê", valorMensal: 900 },
  { id: "custo-2", nome: "Energia elétrica", valorMensal: 180 },
  { id: "custo-3", nome: "Internet", valorMensal: 120 },
  { id: "custo-4", nome: "Marketing (Instagram Ads)", valorMensal: 150 },
];

export const configuracoesSeed: Configuracoes = {
  horasTrabalhoMes: 160,
  multiplicadorPreco: 3,
  custoHoraBambu: 4.5,
};
